// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: command_history.sql

package db

import (
	"context"
)

const createCommandHistory = `-- name: CreateCommandHistory :one
INSERT INTO command_history (
    id,
    session_id,
    command,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, command, created_at, updated_at
`

func (q *Queries) CreateCommandHistory(ctx context.Context, arg CreateCommandHistoryParams) (CommandHistory, error) {
	row := q.queryRow(ctx, q.createCommandHistoryStmt, createCommandHistory,
		arg.ID,
		arg.SessionID,
		arg.Command,
	)
	var i CommandHistory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Command,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionCommandHistory = `-- name: DeleteSessionCommandHistory :exec
DELETE FROM command_history
WHERE session_id = ?
`

func (q *Queries) DeleteSessionCommandHistory(ctx context.Context, arg DeleteSessionCommandHistoryParams) error {
	_, err := q.exec(ctx, q.deleteSessionCommandHistoryStmt, deleteSessionCommandHistory, arg.SessionID)
	return err
}

const getCommandHistoryCount = `-- name: GetCommandHistoryCount :one
SELECT COUNT(*) as count
FROM command_history
WHERE session_id = ?
`

func (q *Queries) GetCommandHistoryCount(ctx context.Context, arg GetCommandHistoryCountParams) (GetCommandHistoryCountRow, error) {
	row := q.queryRow(ctx, q.getCommandHistoryCountStmt, getCommandHistoryCount, arg.SessionID)
	var i GetCommandHistoryCountRow
	err := row.Scan(&i.Count)
	return i, err
}

const listCommandHistoryBySession = `-- name: ListCommandHistoryBySession :many
SELECT id, session_id, command, created_at, updated_at
FROM command_history
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListCommandHistoryBySession(ctx context.Context, arg ListCommandHistoryBySessionParams) ([]CommandHistory, error) {
	rows, err := q.query(ctx, q.listCommandHistoryBySessionStmt, listCommandHistoryBySession, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommandHistory
	for rows.Next() {
		var i CommandHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCommandHistoryBySession = `-- name: ListLatestCommandHistoryBySession :many
SELECT id, session_id, command, created_at, updated_at
FROM command_history
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListLatestCommandHistoryBySession(ctx context.Context, arg ListLatestCommandHistoryBySessionParams) ([]CommandHistory, error) {
	rows, err := q.query(ctx, q.listLatestCommandHistoryBySessionStmt, listLatestCommandHistoryBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommandHistory
	for rows.Next() {
		var i CommandHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}